### ISSUE TITLE
Unknown type 'ViewController'

### ISSUE THREAD

**Issue by adamlucia** [InclementDab/ER7-Gauss-Rifle#5]
I'm getting this error when trying to add the rifle to my Chernarus server

![image](https://github.com/InclementDab/ER7-Gauss-Rifle/assets/2412941/867e2c1d-1aca-4bef-88b5-5b1da6d5d2e5)

**Comment by adamlucia** [comment]
@InclementDab

**Comment by InclementDab** [comment]
run DF bro

**Comment by adamlucia** [comment]
What is DF bro?
